RandomSpawnRatios:
  Andesite: 5
  Amethyst: 1
  Coal: 5
  Cobblestone: 20
  Copper: 1
  Diamond: 1
  Diorite: 3
  Emerald: 1
  Gold: 3
  Granite: 3
  Iron: 4
  Lapis: 2
  Obsidian: 0
  Redstone: 8
  Stone: 0
RandomizeOnStoneCreation: false
RandomizeOnObsidianCreation: false
RandomizationSound: Ssss
AllowedWorlds:
  - world
