name: OreRandomizer
version: "1.1"
main: io.github.crusopaul.OreRandomizer.OreRandomizer
commands:
  ToggleCreeperSound:
    aliases: [or.sound]
    description: Toggles the sound that plays when ore is randomly generated.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /ToggleCreeperSound"
  SetOreRatio:
    aliases: [or.set]
    description: Sets the randomization ratio for the specified ore.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /SetOreRatio <ore> <ratio>"
  GetOreRatio:
    aliases: [or.get]
    description: Displays the randomization ratio for all ores, or one ore if specified.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetOreRatio [ore]"
  AddNewWorld:
    aliases: [or.addWorld]
    description: Allows OreRandomizer to be active for a specified world.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /AddNewWorld <world>"
  GetAllowedWorlds:
    aliases: [or.worlds]
    description: Displays a list or individual world that OreRandomizer is active for.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetAllowedWorlds [world]"
  RemoveAllowedWorld:
    aliases: [or.remWorld]
    description: Makes OreRandomizer inactive for a specified world.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /RemoveAllowedWorld <world>"
permissions:
  OreRandomizer.ToggleCreeperSound:
    description: Allows you to use the command ToggleCreeperSound.
    default: true
  OreRandomizer.SetOreRatio:
    description: Allows you to use the command SetOreRatio.
    default: true
  OreRandomizer.GetOreRatio:
    description: Allows you to use the command GetOreRatio.
    default: true
  OreRandomizer.AddNewWorld:
    description: Allows you to use the command AddNewWorld.
    default: true
  OreRandomizer.GetAllowedWorlds:
    description: Allows you to use the command GetAllowedWorlds.
    default: true
  OreRandomizer.RemoveAllowedWorld:
    description: Allows you to use the command RemoveAllowedWorld.
    default: true
  OreRandomizer.*:
    description: Wildcard permission.
    default: false
    children:
      OreRandomizer.ToggleCreeperSound: true
      OreRandomizer.SetOreRatio: true
      OreRandomizer.GetOreRatio: true
      OreRandomizer.AddNewWorld: true
      OreRandomizer.GetAllowedWorlds: true
      OreRandomizer.RemoveAllowedWorld: true